export const MEMO_TYPE = Symbol.for('oops.memo')
export const PORTAL_TYPE = Symbol.for('oops.portal')
export const CONTEXT_TYPE = Symbol.for('oops.context')
export const PROVIDER_TYPE = Symbol.for('oops.provider')
export const FRAGMENTS_TYPE = Symbol.for('oops.fragments')
export const FORWARD_REF_TYPE = Symbol.for('oops.forwardRef')
