export const MEMO_TYPE = Symbol.for('Oops.memo')
export const LAZY_TYPE = Symbol.for('Oops.lazy')
export const PORTAL_TYPE = Symbol.for('Oops.portal')
export const CONTEXT_TYPE = Symbol.for('Oops.context')
export const PROVIDER_TYPE = Symbol.for('Oops.provider')
export const SUSPENSES_TYPE = Symbol.for('Oops.suspense')
export const FRAGMENTS_TYPE = Symbol.for('Oops.fragments')
export const FORWARD_REF_TYPE = Symbol.for('Oops.forwardRef')